### ISSUE TITLE
How do we feel about using Readonly for props?

### ISSUE THREAD

**Issue by blaketarter** [cremalab/crema-app-web#18]
@roblafeve I wanted to get your current feeling on using `Readonly` for `Props` here, I know we've gone back and forth on it and I've noticed that it may be confusing while not achieving much.

https://github.com/cremalab/crema-app-web/blob/3644569ab71acf67a0209c536fcf1f23d8720c5f/_templates/component/new/index.ejs.t#L12

**Comment by roblafeve** [comment]
@blaketarter yeah—I'm not sure where we've landed here. It may be worth digging deeper into this to see if it's actually something React guarantees already. If so, should we be using a React-provided interface to annotate our components?

**Comment by blaketarter** [comment]
There is always the `React.SFC` interface.

**Comment by roblafeve** [comment]
@blaketarter @KileyAdams92 we talked about this yesterday, but I wasn't sure where we landed. We discussed:

- Do we use `Readonly<Props>` in the first place (I still think there is some value to using it)
- Swapping out `children` with something like `name` as the initial generated props

I'd love to see a PR in either case 👍

**Comment by kileybublitz** [comment]
I like the second option. 

After we decide, I can make the changes/PR.

**Comment by blaketarter** [comment]
I definitely agree with the second point.

**Comment by roblafeve** [comment]
So is it accurate to say: "We will change the shape of the component (e.g. `children` → `name`) . We will maintain `Readonly<Props>`."?

**Comment by kileybublitz** [comment]
I was thinking about this earlier, trying to think of something that would be 'generic'. But would something like `genericProp` make more/the same/less sense as just using something simple like `name`?  ¯\_(ツ)_/¯

**Comment by roblafeve** [comment]
I think displaying the name via `name` prop is pretty clear. `genericProp` takes more mental energy to make sense of, especially if the test/story components are applied with the components name initially. I like using the components name as a default thing to display for easy identification in the accidentally generated snapshot or when you're just trying to find the storybook story to start workin' on it. Those my thoughts 🤔

**Comment by kileybublitz** [comment]
Cool, that makes sense. I'll figure out making the change from `children` ->  `name` here in a bit.

**Comment by roblafeve** [comment]
@KileyAdams92 be sure to claim this issue if you're taking it on 👍

**Comment by roblafeve** [comment]
Also, see the project for communicating progress: https://github.com/cremalab/crema-app-web/projects/1

**Comment by kileybublitz** [comment]
@roblafeve I assigned myself to this issue, is that all I need to do to claim it?
