### ISSUE TITLE
Do not track coverage on src/storybookSetup.tsx

### ISSUE THREAD

**Issue by roblafeve** [cremalab/crema-app-web#199]
**Describe the bug**
Code coverage is down to 40% with the introduction of a new config-level file (`src/storybookSetup.tsx`). This just needs to be added to coverage config.

**To Reproduce**
1. Go to [repo](https://github.com/cremalab/app-web#crema-app---web-)

**Expected behavior**
I expect this to be 100%

**Screenshots**
![image](https://user-images.githubusercontent.com/157195/76632176-c8256f00-6510-11ea-9c14-8bffdb6110d4.png)

**Comment by blaketarter** [comment]
Is there an issue with the codecov integration, I thought it used to comment on PRs?

**Comment by roblafeve** [comment]
I'm assuming/hoping it's something that was unique to GitHub opening that PR up??? https://github.com/cremalab/app-web/pull/197

**Comment by roblafeve** [comment]
Oh, yeah it must not be working 🤔 https://github.com/cremalab/app-web/pull/198

**Comment by roblafeve** [comment]
@blaketarter oh—yeah the move to GitHub actions has changed this behavior. I think it's related to this: https://github.com/cremalab/app-web/runs/496363278#step:6:20

**Comment by roblafeve** [comment]
It's working now.
