### ISSUE TITLE
Outline how CAW is best utilized by other projects

### ISSUE THREAD

**Issue by roblafeve** [cremalab/crema-app-web#22]
The usefulness of this effort will be heavily affected by how easily we can share updates across projects that use it. We have been operating under the assumption that this is mainly a boilerplate that though some effort a forked project could be updated against down the road.

What would it look like to distribute this code as a package in the vein of `create-react-app`'s `react-scripts`. There would likely be a devision between what is currently housed in this repo and what would belong in a package like this—utils, generators, ESLint/prettier config. If we go this route we need to do some research into how to best achieve it. Being able to consume this for web, mobile, and API projects should also be a goal (because who has time to maintain three of these 😖).

**Comment by blaketarter** [comment]
Something to keep in mind is the more that we put behind a package à-la `react-scripts` the less that consumers will be able to customize to their needs. In a lot of cases this is a good thing, but for something like how `storybook` or `webdriver` are configured there may need to be a way for consumers to customize it.

**Comment by roblafeve** [comment]
@blaketarter yup—that's what we need to figure out 👍

**Comment by roblafeve** [comment]
For now—we are maintaining this as a template repo. Let's reassess in the future 👍
