### ISSUE TITLE
Research/Thoughts on Test Scripts

### ISSUE THREAD

**Issue by kileybublitz** [cremalab/crema-app-web#23]
When testing all of the Test Scripts, I ran into 2 scripts that did not run:

`test:e2e` fails even when app is running
`test:unit:coverage:ci` fails stating `sh: codecov: command not found`

After talking to @roblafeve, maybe the `test:unit:coverage:ci` doesn't run yet due to codecov being run on Travis when code is pushed. 🤷‍♀ 

I just wanted to start this issue so we could discuss these two test scripts (if they are working as expected, can we make them better, do we need to change something in our process)

@blaketarter @roblafeve what do you think?

**Comment by roblafeve** [comment]
I think this has been addressed. Closing...
