### ISSUE TITLE
Test Scripts

### ISSUE THREAD

**Issue by roblafeve** [cremalab/crema-app-web#3]
Ensure that all listed scripts work.

## Scripts:
- [x] `build`
- [x] `new:component`
- [x] `new:util`
- [x] `prepush`
- [x] `start:ci`
- [x] `start`
- [x] `static`
- [x] `test:analyze`
- [x] `test:ci`
- [x] `test:e2e:ci`
- [ ] `test:e2e`
- [x] `test:lint:fix`
- [x] `test:lint`
- [x] `test:playground:build`
- [x] `test:playground`
- [x] `test:unit:coverage`
- [ ] `test:unit:coverage:ci`
- [x] `test:unit:coverage:watch`
- [x] `test:unit`
- [x] `test:visual:approve`
- [x] `test:visual:ci`
- [x] `test:visual:update`
- [x] `test:visual`
- [x] `test`

**Comment by kileybublitz** [comment]
@roblafeve is this still something you are working on/need help with?

**Comment by roblafeve** [comment]
@KileyAdams92 I think it would be good to have someone go through and test all these. It's always enlightening when it's not someone who is super close to it 😄

**Comment by kileybublitz** [comment]
And when you say test you mean just running them and making sure they do what they need to?

**Comment by kileybublitz** [comment]
When running `npm run test:analyze` - this was the result in my terminal:
<img width="557" alt="Screen Shot 2019-05-09 at 1 13 42 PM" src="https://user-images.githubusercontent.com/31576550/57476552-7828ac80-725c-11e9-819e-7b41356f915d.png">
Not sure if the `[undefined] Unable to map 123/1112 bytes (11.06%)` is a problem.

this was the result on my browser:
<img width="699" alt="Screen Shot 2019-05-09 at 1 13 49 PM" src="https://user-images.githubusercontent.com/31576550/57476556-7b239d00-725c-11e9-8e35-f98af7321867.png">

**Comment by blaketarter** [comment]
@KileyAdams92 I _think_ that's okay, I didn't set up that script though so I'll defer to @roblafeve.

**Comment by kileybublitz** [comment]
result of `npm run test:e2e`:

<img width="641" alt="Screen Shot 2019-05-09 at 1 23 45 PM" src="https://user-images.githubusercontent.com/31576550/57477403-3ac51e80-725e-11e9-888c-60b14d1355b7.png">

*note that I had run `npm start` in another terminal prior to running `npm run test:e2e`

**Comment by kileybublitz** [comment]
Things to note after running through the above scripts:

1. Need feedback from @roblafeve on test:analyze (see screenshots above)
2.  `npm run test:e2e` does not work and returns the above screenshot, with `npm start` running with no errors in another terminal
3. `test` effectively does the same task as `test:unit`
4. The following scripts have been added since this task was created and also need to be tested: 
`test:unit:coverage:watch`
`test:unit:coverage:ci`

**Comment by roblafeve** [comment]
@KileyAdams92 awesome! Thanks for running through these. 

- `test:analyze`: this is working as expected
- `test:e2e`: expected to fail in this case (though it might need to change)
- `test`: it's being referenced in other scripts, let's leave it
-  `test:unit:coverage:watch` & `test:unit:coverage:ci`: let's test 'em 😄

**Comment by kileybublitz** [comment]
Final notes after testing: 

1. `test:e2e` fails even when app is running
2. `test:unit:coverage:ci` fails stating `sh: codecov: command not found`

**Comment by kileybublitz** [comment]
I'm going to close this issue and make a new issue for the two tests that aren't/maybe aren't supposed to be working. 👍
