### ISSUE TITLE
Theme Provider for Storybook

### ISSUE THREAD

**Issue by itwaze** [cremalab/crema-app-web#382]
When I try to connect crema theme providers:

```
const StylesDecorator = (storyFn) => (
  <ContextProvider>
    <CremaThemeProvider>{storyFn()}</CremaThemeProvider>
  </ContextProvider>
);

addDecorator(StylesDecorator);
```
this case doesn't work, but if I connect `ThemeProvider` form `@material-ui` - all is well. How do I can correctly connect crema theme provider?

**Comment by roblafeve** [comment]
@itwaze where are you attempting to import `CremaThemeProvider` from? As far as I'm aware, this component doesn't exist. We don't prescribe any theming solution, so using MUI would be the way to go in this case.

**Comment by itwaze** [comment]
@roblafeve already connected, thanks for the answer
