### ISSUE TITLE
Add testing-library/eslint-plugin-testing-library

### ISSUE THREAD

**Issue by blaketarter** [cremalab/crema-app-web#388]
**Is your feature request related to a problem? Please describe.**

When using testing-library there are some common pitfalls around when to use async and which form of element selectors to use. 

**Describe the solution you'd like**

https://github.com/testing-library/eslint-plugin-testing-library is an eslint plugin that can help resolve those common pitfalls.

**Describe alternatives you've considered**

N/A

**Additional context**

We should consider using both the `testing-library/recommended` and `testing-library/react` rulesets.

**Comment by luiz-chagas** [comment]
Fixed on #1039
