### ISSUE TITLE
Ensure unit test files are type checked properly

### ISSUE THREAD

**Issue by blaketarter** [cremalab/crema-app-web#43]
I've noticed that unit test files are not type checked as a part of our current build/test process. We should find a way to ensure that there are no type errors before passing all tests.

**Comment by blaketarter** [comment]
@roblafeve I'm trying out a fix on my project where I just added a new script 
```
"test:types": "tsc",
```

that runs as a part of the prepush script. What are you thoughts on this or another way to solve the problem?

**Comment by roblafeve** [comment]
I'm pro that

**Comment by blaketarter** [comment]
👍 I'll get a PR up that includes that fix then.

**Comment by roblafeve** [comment]
Feel free to add tickets here: https://crema.atlassian.net/jira/software/projects/CAW/boards/79
