### ISSUE TITLE
Example code errors

### ISSUE THREAD

**Issue by kileybublitz** [cremalab/crema-app-web#437]
**Describe the bug**
When creating a new component, I opted to have example code populated. This is the code that was generated for styling: 

```
const styles = StyleSheet.create({
  container: {},
})
```
The following error is present: 
```
Property 'create' does not exist on type '{ new (): StyleSheet; prototype: StyleSheet; }'.ts(2339)
```

**To Reproduce**
1. Run 'npm run new:component` and follow the prompts.
2. Select yes when asked if you want the component generated with example code.
3. View component.

**Expected behavior**
I would expect no errors after running an npm install. 

**Screenshots**
<img width="794" alt="Screen Shot 2020-09-10 at 2 39 25 PM" src="https://user-images.githubusercontent.com/31576550/92793811-5bcae180-f374-11ea-8bc1-7c7cc17eacfa.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6
 - Browser: chrome
 - Version 85.0.4183.83

**Additional context**
@blaketarter said we might have had a merge mixup and some mobile code might have made it's way into the app-web

**Comment by blaketarter** [comment]
@roblafeve I think this might be related to https://github.com/cremalab/scripts using the wrong template file for the web repo.

**Comment by roblafeve** [comment]
Oh, that's not good!

**Comment by roblafeve** [comment]
@blaketarter it looks like the right script is getting referenced but the content of that template is the mobile version—I must have done something dumb. 🤷

**Comment by blaketarter** [comment]
@roblafeve This is resolved now with the latest version of `cremalab/scripts` right?

**Comment by roblafeve** [comment]
@blaketarter yep, this one is completely resolved.
