### ISSUE TITLE
Test/Stories Errors

### ISSUE THREAD

**Issue by kileybublitz** [cremalab/crema-app-web#440]
**Describe the bug**
When running `npm run new:component` and choosing to have example code generated:

1.  The story file includes a `name` property on the component. However, the component itself does not have a name property which causes an error every time. 

2. In the test file, the order of the imports has to be corrected each time and there is an import from `"@testing-library/react-native"`

**To Reproduce**
1. Run `npm run new:component`
2. Choose to have example code generated
3. View both the stories file and test file of your new component

**Expected behavior**
No errors when you initially create a component and also no mobile imports

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 85.0.4183.102

**Comment by blaketarter** [comment]
@roblafeve This is also resolved with the latest version of `cremalab/scripts` right?

**Comment by roblafeve** [comment]
@blaketarter I believe this is _mostly_ resolved—though in one of the example variants there is still a type error. I'm going to add type-checking to the tests for all generators to avoid this in the future.

**Comment by roblafeve** [comment]
Fixed
