### ISSUE TITLE
Consider adding a bot to help maintain minor dependency bumps

### ISSUE THREAD

**Issue by blaketarter** [cremalab/crema-app-web#48]
Maybe something like https://github.com/marketplace/renovate? @roblafeve what do you think?

**Comment by roblafeve** [comment]
I love this. Do it.

**Comment by roblafeve** [comment]
@blaketarter I've added it to this repo. Not sure what the next steps are from here. Let me know 👍

**Comment by blaketarter** [comment]
@roblafeve Awesome I'll work on getting it configured!
