### ISSUE TITLE
Consider adding `@testing-library/cypress`

### ISSUE THREAD

**Issue by roblafeve** [cremalab/crema-app-web#707]
`@testing-library/cypress` adds some very convenient selectors and harmonizes some of the API between Integration and Unit tests.

I'm not sure if this is the type of thing that goes beyond the bounds of this template, but I'm interested in having that conversation. If anything should have "batteries included" it should be the tooling.

CC @blaketarter

**Comment by blaketarter** [comment]
@roblafeve Ah yeah, good idea! I think it belongs in here for sure.
