### ISSUE TITLE
Remove Loki

### ISSUE THREAD

**Issue by roblafeve** [cremalab/crema-app-web#818]
Loki has proven to be a non-essential tool that doesn't constitute a "default". It has added complexity and generally confuses folks. Additionally, it tends to be somewhat flaky—tests fail inconsistently and project owners tend to disable it as a result. Because of this, we should remove it and allow individual teams to opt into tools like this. 

This would require the removal of Loki-related text from our generators in `@cremalab/scripts`

**Comment by roblafeve** [comment]
@blaketarter do you concur?

**Comment by blaketarter** [comment]
I do!
